name: zincsoap-ml
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=20_gnu
  - anyio=4.12.1=pyhcf101f3_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py310h29418f3_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.2.0=pyhcf101f3_0
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.6=hdf23a24_1
  - aws-c-cal=0.9.13=h46f3b43_1
  - aws-c-common=0.12.6=hfd05255_0
  - aws-c-compression=0.3.2=hcb3a2da_0
  - aws-c-event-stream=0.5.9=h972bbec_2
  - aws-c-http=0.10.10=hb410799_0
  - aws-c-io=0.26.1=h0d5b9f9_1
  - aws-c-mqtt=0.14.0=h833cf40_1
  - aws-c-s3=0.11.5=h3ec5e31_3
  - aws-c-sdkutils=0.2.4=hcb3a2da_4
  - aws-checksums=0.2.10=hcb3a2da_0
  - aws-crt-cpp=0.37.2=h5e571c5_3
  - aws-sdk-cpp=1.11.606=ha60a6cd_13
  - azure-core-cpp=1.16.2=h49e36cd_0
  - azure-identity-cpp=1.13.3=h5ffce34_1
  - azure-storage-blobs-cpp=12.16.0=hcd625b1_1
  - azure-storage-common-cpp=12.12.0=h5ffce34_1
  - azure-storage-files-datalake-cpp=12.14.0=h1678c0b_1
  - babel=2.18.0=pyhcf101f3_0
  - backports.zstd=1.3.0=py310h458dff3_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - bleach=6.3.0=pyhcf101f3_1
  - bleach-with-css=6.3.0=hbca2aae_1
  - bokeh=3.8.2=pyhd8ed1ab_0
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - brotli-python=1.2.0=py310hfff998d_1
  - bzip2=1.0.8=h0ad9c76_9
  - c-ares=1.34.6=hfd05255_0
  - ca-certificates=2026.1.4=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h477c42c_1
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py310h29418f3_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyha7b4d00_1
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.2=py310hc19bc0b_0
  - cycler=0.12.1=pyhcf101f3_2
  - cytoolz=1.1.0=py310h29418f3_1
  - dask=2026.1.2=pyhcf101f3_1
  - dask-core=2026.1.2=pyhcf101f3_0
  - dask-image=2025.11.0=pyhd8ed1ab_0
  - debugpy=1.8.20=py310h699e580_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distributed=2026.1.2=pyhcf101f3_1
  - double-conversion=3.4.0=hac47afa_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.17.1=hd47e2ca_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py310hdb0e946_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=h57928b3_0
  - fribidi=1.0.16=hfd05255_0
  - fsspec=2026.2.0=pyhd8ed1ab_0
  - glib=2.86.4=h19e2e61_0
  - glib-tools=2.86.4=he647baa_0
  - graphite2=1.3.14=hac47afa_2
  - gst-plugins-base=1.26.10=hf40947b_0
  - gstreamer=1.26.10=h54009fa_0
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.15.1=nompi_py310hb7e4da9_101
  - harfbuzz=12.3.2=h5a1b470_0
  - hdf5=1.14.6=nompi_hae35d4c_106
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - hyperspy=2.4.0=pyhd8ed1ab_0
  - hyperspy-base=2.4.0=pyhd8ed1ab_0
  - hyperspy-gui-ipywidgets=2.1.0=pyhd8ed1ab_0
  - hyperspy-gui-traitsui=2.1.1=pyhd8ed1ab_0
  - icu=78.2=h637d24d_0
  - idna=3.11=pyhd8ed1ab_0
  - imagecodecs-lite=2019.12.3=py310hb0944cc_8
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=7.2.0=pyh6dadd2b_1
  - ipympl=0.10.0=pyhcf101f3_0
  - ipython=8.37.0=pyha7b4d00_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - json5=0.13.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.26.0=pyhcf101f3_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.26.0=hcf101f3_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - jupyter_events=0.12.0=pyhe01879c_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.4=pyhcf101f3_0
  - jupyterlab=4.5.4=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - kiwisolver=1.4.9=py310h1e1005b_2
  - krb5=1.21.3=hdf4eb48_0
  - lark=1.3.1=pyhd8ed1ab_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.18=hf2c6c5f_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20260107.1=cxx17_h0eb2380_0
  - libaec=1.1.5=haf901d7_0
  - libarrow=23.0.1=hfb55bc1_2_cpu
  - libarrow-acero=23.0.1=h7d8d6a5_2_cpu
  - libarrow-compute=23.0.1=h081cd8e_2_cpu
  - libarrow-dataset=23.0.1=h7d8d6a5_2_cpu
  - libarrow-substrait=23.0.1=h524e9bd_2_cpu
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libclang13=21.1.8=default_ha2db4b5_3
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.18.0=h43ecb02_0
  - libdeflate=1.25=h51727cc_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.4=hac47afa_0
  - libffi=3.5.2=h3d046cb_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_18
  - libglib=2.86.4=h0c9aed9_0
  - libgomp=15.2.0=h8ee18e1_18
  - libgoogle-cloud=2.39.0=h01c467a_1
  - libgoogle-cloud-storage=2.39.0=he04ea4c_1
  - libgrpc=1.78.0=h9ff2b3e_1
  - libhwloc=2.12.2=default_h4379cf1_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - liblzma=5.8.2=hfd05255_0
  - libogg=1.3.5=h2466b09_1
  - libparquet=23.0.1=h7051d1f_2_cpu
  - libpng=1.6.55=h7351971_0
  - libprotobuf=6.33.5=h61fc761_0
  - libre2-11=2025.11.05=h04e5de1_1
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.51.2=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.22.0=h23985f6_1
  - libtiff=4.7.1=h8f73337_1
  - libutf8proc=2.11.3=hb980946_0
  - libvorbis=1.3.7=h5112557_2
  - libvulkan-loader=1.4.341.0=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=h779ef1b_1
  - libxml2-16=2.15.1=h3cfd58e_1
  - libxslt=1.1.43=h0fbe4c1_1
  - libzlib=1.3.1=h2466b09_2
  - link-traits=1.0.3=pyhd8ed1ab_4
  - llvm-openmp=21.1.8=h4fa8253_0
  - llvmlite=0.46.0=py310hfe4b161_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.5=py310hd705207_1
  - lz4-c=1.10.0=h2466b09_1
  - markupsafe=3.0.3=py310hdb0e946_0
  - matplotlib=3.10.8=py310h5588dad_0
  - matplotlib-base=3.10.8=py310h0bdd906_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mistune=3.2.0=pyhcf101f3_0
  - mkl=2025.3.0=hac47afa_455
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.2=py310he9f1925_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.16.0=pyhcf101f3_0
  - natsort=8.4.0=pyhcf101f3_2
  - nbclient=0.10.4=pyhd8ed1ab_0
  - nbconvert-core=7.17.0=pyhcf101f3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numba=0.63.1=py310h04bad52_0
  - numexpr=2.14.1=mkl_py310hc3dba39_1
  - numpy=1.26.4=py310hf667824_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.1=hf411b9b_1
  - orc=2.2.2=h0a1ad0e_1
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=26.0=pyhcf101f3_0
  - pandas=2.3.3=py310hed136d8_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.4=h03d888a_0
  - parso=0.8.6=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.47=hd2b5f0e_0
  - pentapy=1.4.1=py310h8f3aa81_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=12.1.1=py310h712baa7_0
  - pims=0.7=pyhd8ed1ab_1
  - pint=0.24.4=pyhe01879c_2
  - pip=26.0.1=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.9.2=pyhcf101f3_0
  - ply=3.11=pyhd8ed1ab_3
  - prettytable=3.17.0=pyhd8ed1ab_0
  - prometheus_client=0.24.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.2=py310h1637853_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow-core=23.0.1=py310hc34f82c_0_cpu
  - pybaselines=1.2.1=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pyface=8.0.0=pyhd8ed1ab_2
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyqt=5.15.11=py310hdf200a9_2
  - pyqt5-sip=12.17.0=py310h73ae2b4_2
  - pyside6=6.10.2=py310h96c60bd_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.10.19=hc20f281_3_cpython
  - python-box=7.3.3=py310h29418f3_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pywavelets=1.8.0=py310hb0944cc_0
  - pywin32=311=py310h282bd7d_1
  - pywinpty=2.0.15=py310h9e98ed7_1
  - pyyaml=6.0.3=py310hdb0e946_1
  - pyzmq=27.1.0=py310h78cba24_1
  - qhull=2020.2=hc790b64_5
  - qt-main=5.15.15=he584256_7
  - qt6-main=6.10.2=h68b6638_4
  - re2=2025.11.05=ha104f34_1
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhcf101f3_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rosettasciio-base=0.12.0=py310h29418f3_0
  - rpds-py=0.30.0=py310h034784e_0
  - ruamel.yaml=0.19.1=pyhcf101f3_0
  - ruamel.yaml.clib=0.2.15=py310h1637853_1
  - scikit-image=0.20.0=py310h1c4a608_1
  - scikit-learn=1.7.2=py310h21054b0_0
  - scipy=1.15.2=py310h15c175c_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=2.1.0=pyh6dadd2b_1
  - setuptools=82.0.0=pyh332efcf_0
  - sip=6.10.0=py310h73ae2b4_1
  - six=1.17.0=pyhe01879c_1
  - slicerator=1.1.0=pyhd8ed1ab_1
  - snappy=1.2.2=h7fa0ca8_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.8.3=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.6=py310h8f3aa81_0
  - sympy=1.14.0=pyh04b8f61_5
  - tbb=2022.3.0=h3155e25_2
  - tblib=3.2.2=pyhcf101f3_0
  - terminado=0.18.1=pyh6dadd2b_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tifffile=2020.6.3=py_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h6ed50ae_3
  - toml=0.10.2=pyhcf101f3_3
  - tomli=2.4.0=pyhcf101f3_0
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.4=py310h29418f3_0
  - tqdm=4.67.3=pyha7b4d00_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - traits=7.1.0=py310h29418f3_0
  - traitsui=8.0.0=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025c=hc9c84f9_1
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=17.0.1=py310h29418f3_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - vs2015_runtime=14.44.35208=h38c0c73_34
  - wcwidth=0.6.0=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.46.3=pyhd8ed1ab_0
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - yaml=0.2.5=h6a83c73_3
  - zeromq=4.3.5=h5bddc39_9
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib-ng=2.3.3=h0261ad2_1
  - zstd=1.5.7=h534d264_6
  - pip:
      - pyarrow==23.0.1
prefix: C:\Users\elise\miniforge3\envs\zincsoap-ml
