name: zincsoap-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - matplotlib
  - matplotlib-scalebar
  - scikit-learn
  - hyperspy
  - exspy
  - hyperspy-gui-ipywidgets
  - jupyterlab
  - ipykernel
  - ipywidgets
  - seaborn
  - tqdm